# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate sys-info

Name:           rust-%{crate}
Version:        0.5.3
Release:        1%{?dist}
Summary:        Get system information in Rust

License:        MIT
URL:            https://crates.io/crates/sys-info
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate
# Initial patched metadata
# * Replace gcc with cc, https://github.com/FillZpp/sys-info-rs/pull/21
Patch0:         sys-info-0.5.3-fix-metadata.diff
# Finish gcc->cc
Patch1:         0001-port-to-cc-crate.patch

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
# [dependencies]
BuildRequires:  (crate(libc) >= 0.2.29 with crate(libc) < 0.3.0)
# [build-dependencies]
BuildRequires:  (crate(cc) >= 1.0.0 with crate(cc) < 2.0.0)
BuildRequires:  %{_bindir}/hostname

%description
%{summary}.

%package        devel
Summary:        %{summary}
Requires:       %{_bindir}/hostname
BuildArch:      noarch

%description    devel
Get system information in Rust.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files          devel
%license LICENSE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Mon Dec 04 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.5.3-1
- Initial package
